### ISSUE TITLE
Package versions

### ISSUE THREAD

**Issue by esb5324** [jaydu1/scVAEIT#4]
Hello,
I have been having trouble setting up a conda environment with the required packages. Is there any flexibility with any of the versions, so I can try and see if that works? I have been getting errors where it seems like the versions are in conflict with each other. Thank you for your advice!
Elle

**Comment by jaydu1** [comment]
Hi, can u provide the platform: win/linux/maxos?
I am aware of some package conflicts on wins using conda-forge.

You can use inexact version requirements, e.g. `conda install 'matplotlib>=1.4.3'` to try to avoid the some of the conflicts.

**Comment by esb5324** [comment]
Hi Jinhong,

Thanks for your quick response. I am using Linux.

Elle
________________________________

**Comment by jaydu1** [comment]
The main dependencies are `tensorflow` and `tensorflow-probability`.

I just tested on the updated versions of these packages:
```
# Name                    Version                   Build  Channel
h5py                      3.9.0           nompi_py311h3839ddf_103    conda-forge
numpy                     1.26.0          py311h64a7726_0    conda-forge
pandas                    2.1.1           py311h320fe9a_1    conda-forge
python                    3.11.5          hab00c5b_0_cpython    conda-forge
scikit-learn              1.3.1           py311hc009520_0    conda-forge
scipy                     1.11.3          py311h64a7726_0    conda-forge
tensorflow                2.12.1          cuda112py311h63ba870_0    conda-forge
tensorflow-base           2.12.1          cuda112py311hb0f8ee9_0    conda-forge
tensorflow-estimator      2.12.1          cuda112py311h9aaad64_0    conda-forge
tensorflow-gpu            2.12.1          cuda112py311h0bbbad9_0    conda-forge
tensorflow-probability    0.20.0             pyhd8ed1ab_0    conda-forge
```
It seems to also work. Let me know if you still encouter any problem.

**Comment by jaydu1** [comment]
I have formally tested it on the updated packages.
You can follow the instructions here to create a conda environment (if you don't have `mamba`, simply replace it by `conda`):

```
mamba create --name tf python=3.9 -y
conda activate tf
mamba install -c conda-forge "tensorflow>=2.12" "tensorflow-probability>=0.12" pandas jupyter -y
mamba install -c conda-forge "scanpy>=1.9.2" matplotlib scikit-learn -y
```

The UMAP visualizations will be slightly effected by `scanpy` and `umap-learn` version, though they are similar to those in the paper.

**Comment by esb5324** [comment]
Thank you! I had to upgrade numpy to 1.22.4 + and run pip install tensorflow-addons, and then it worked.


Elle Tang
Pronouns: she/her/hers
Statistics Ph.D. student

________________________________
