### ISSUE TITLE
Available for single modality integration?

### ISSUE THREAD

**Issue by adamtongji** [jaydu1/scVAEIT#6]
Hi, thank you for your tools and paper for multimodal mosaic integration!
I hope to integrate datasets of multiome(RNA+ATAC) and scRNA. But your tutorials only mentioned multimodal integrations with at least two modalities. 
Does scVAEIT support  mosaic integration with single modality of scRNA, scATAC or ADT?

**Comment by jaydu1** [comment]
Hi, thanks for your interest! 
Regarding your questions, yes, scVAEIT supports the imputation for multiple datasets with the same modality.

I have added an example to demonstrate the usage in this case [example/imputation_1modality.ipynb](https://github.com/jaydu1/scVAEIT/blob/4b8a4ae99d8a48be49876e88909b1981da054b1d/example/imputation_1modality.ipynb).

Let me know if you have any questions and if anything needs to be clarified for the parameter setup.
