### ISSUE TITLE
Request for Data Access

### ISSUE THREAD

**Issue by pondandmoon** [jaydu1/scVAEIT#7]
Hello, thank you for your excellent work. I'm very interested in the scVAEIT method. I've encountered the same issue of not being able to find the DOGMA_pbmc.h5 file. If possible, could you please share this data with me? I would greatly appreciate it. My email is pondandmoon@gmail.com. Thank you!

**Comment by jaydu1** [comment]
Hi, thanks for your interest. Please find the dataset through the link [here](https://drive.google.com/drive/folders/19bzIGKex9Cwoy3ZWXra6D2hvqDtZOvfB?usp=drive_link) to Google Drive.

**Comment by pondandmoon** [comment]
Data received, much appreciated for your sharing!
