### ISSUE TITLE
Reproduce pbmc_scVAEIT. py

### ISSUE THREAD

**Issue by zhangxueting233** [jaydu1/scVAEIT#8]
There is a slight issue with the reproduction you posted,   
model = VAEIT(config, data[cell_types!=cell_type_test])
TypeError: __init__() missing 1 required positional argument: 'masks'
how to solve this question？

**Comment by jaydu1** [comment]
For reproducibility, please use the package version located at `/Reproducibility materials/scVAEIT` instead of the latest version in the project root.

**Comment by jaydu1** [comment]
If you are looking at the notebook example in the root directory, it does not allow loading the weight file in the `Reproducibility materials` directly. I will update the example soon, with the updated weight files.

**Comment by jaydu1** [comment]
Hi, for reproducing the results in the paper, please use the module at [`/Reproducibility materials/scVAEIT`](https://github.com/jaydu1/scVAEIT/tree/main/Reproducibility%20materials/scVAEIT).
For other purposes, please consider using the updated package v1.0.0; the corresponding weight files are available for running [`example/integration_3modalities.ipynb`](https://github.com/jaydu1/scVAEIT/blob/main/example/integration_3modalities.ipynb).
