### ISSUE TITLE
scVAEIT for Mosaic Integration without global Shared Features

### ISSUE THREAD

**Issue by pondandmoon** [jaydu1/scVAEIT#9]
Hi,

I'm very interested in the scVAEIT method and would like to ask if it is suitable for mosaic integration tasks where there are no globally shared features across batches. For example, in one batch, we have scRNA-seq + scATAC-seq data, while in the second batch we only have scRNA-seq data, and in the third batch we only have scATAC-seq data.

Would scVAEIT still be applicable in this case?

Thank you in advance for your insights!

**Comment by jaydu1** [comment]
Hi, thanks for your interest, and sorry for the late reply. Yes, it is definitely suitable for the setting you describe. In that case, the model can learn to translate between the two modalities from the joint measurement. However, caution should be warranted if the joint measurements (scRNA-seq + scATAC-seq) are of small sample sizes.

**Comment by pondandmoon** [comment]
Hi jaydu1,

Thank you for your explanation. And look forward to your more outstanding work.
